


---
  - name: Create and mount new storage
    hosts: ceph-1
   
    tasks:
     - name: create new partition
       parted:
        name: files
        label: gpt
        device: /dev/sdc
        number: 1
        state: present
        part_start: 1MiB
        part_end: 1GiB

     - name: Create xfs filesystem
       filesystem:
          dev: /dev/sdc1
          fstype: xfs

     - name: Create mount directory
       file:
         path: /data
         state: directory

     - name: mount the filesystem
       mount:
        path: /data
        src: /dev/sdc1
        fstype: xfs
        state: mounted
